#quastion number 1
```{r}
a<- c(1:3)
b<- c(4:6)
c<- c(7:9)

r<- cbind(a,b,c
)

mymatrix<- matrix(
  r,
  ncol = 3, nrow = 3
)

print(mymatrix)


```
#quastion number 2
```{r}
id<- c(1:5)
name<- c("Sara","Ehsan","Ragu","john","Ronaldo")
family<- c("Jorjia","Fard","bayyer","wick","armando")
Phone_number<- c(334567,54124455,343434,987776,8543222)
location<- c("Montreal","Tehran","delhi","toronto","paris")

employees_data_frame <- data.frame(id = id,name = name,family = family, Phone_number = Phone_number, location = location)
print(employees_data_frame)
summary(employees_data_frame)
```
#quastion number 3
```{r}
my_matrix = matrix(
  c(1:16),
  nrow = 4,  
  ncol = 4,        
  byrow = TRUE         
)
  
# Naming rows
rownames(my_matrix) = c("row1", "row2", "row3","row4")
  
# Naming columns
colnames(my_matrix) = c("col1", "col2", "col3","col4")
  
cat("Original matrix:\n")
print(my_matrix)
```
```{r}
#3rd column and 2nd row
print(my_matrix[2,3])
#the 3rd row and only the 4th column 
print(my_matrix[3,4])
```
#quastion number 4
```{r}
m1 = my_matrix = matrix(
  c(1:9),
  nrow = 3,  
  ncol = 3,        
  byrow = TRUE         
)
m2 = my_matrix = matrix(
  c(21:29),
  nrow = 3,  
  ncol = 3,        
  byrow = TRUE         
)

combine_data<- rbind(m1,m2)

print(combine_data)


```

#quastion number 5

```{r}

bmicalculator<- function(h,w)
{
  #The formula for BMI is weight in kilograms divided by height in meters squared
  h<- h/100 #centimeters to meters
  result = w / (h * h) 
  return(result)
}

cat("Please enter your weight in kilograms:\n")
Weight = readline();
cat("Please enter your height in centimeters:\n")
height = readline();

Weight<- as.double(Weight)
height<- as.double(height)

bmi<- bmicalculator(height,Weight)


print(result)
```



#quastion number 6

```{r}


m1 = my_matrix = matrix(
  c(1:6),
  nrow = 2,  
  ncol = 3,        
  byrow = TRUE         
)
m2 = my_matrix = matrix(
  c(21:26),
  nrow = 2,  
  ncol = 3,        
  byrow = TRUE         
)

combine_data<- rbind(m1,m2)

df<- as.data.frame(combine_data)

print(df)
```

#quastion number 7

```{r}
Parameter<- c("Alpha","Beta","Beta","Alpha","Alpha","Beta","Beta")
State<- c("Active","Active","Passive","Passive","Passive","Active","Passive")
Value<- c(50,45,25,21,26,30,18)
Dependents<- c(2,5,0,0,1,2,0)

my_data_frame<- data.frame(Parameter,State,Value,Dependents)

my_data_frame2 <- subset(my_data_frame,Parameter=="Alpha")

print(my_data_frame2)


```

```{r}
read_csv = read.csv('CADUSD=X.csv',sep=',')
read_csv<- as.data.frame(read_csv)
print(read_csv)
```
```{r}
barplot(read_csv$Open, main="Open in Diffrents Dates", xlab="Date", horiz=TRUE)
```


```{r}
boxplot(read_csv$High, main="High", xlab="High in Date", ylab="Date", col = "yellow",
        horizontal = TRUE)
```



```{r}
hist(read_csv$Open, col="yellow", freq = TRUE)
```








```{r}
#quastion number 12

m1 = my_matrix = matrix(
  c(1:9),
  nrow = 3,  
  ncol = 3,        
  byrow = TRUE         
)


my_array<- as.array(m1)

print(m1)




```

```{r}
#quastion number 13

m1 = matrix(
  c(1:9),
  nrow = 3,  
  ncol = 3,        
  byrow = TRUE         
)
m2 = matrix(
  c(31:39),
  nrow = 3,  
  ncol = 3,        
  byrow = TRUE         
)

combine_data<- rbind(m1,m2)

my_array<- as.array(combine_data)


print(my_array)
```


```{r}
#quastion number 14
m1 = matrix(
  c(1:6),
  nrow = 2,  
  ncol = 3,        
  byrow = TRUE         
)
m2 = matrix(
  c(11:16),
  nrow = 2,  
  ncol = 3,        
  byrow = TRUE         
)
print(m1+m2)
print(m1-m2)
print(m1*m2)
print(m1/m2)
```

```{r}
#web subscription, which cost $10 a month
#They boost the post for four days with a budget of $25 per day
#they received 100 visitors and 20 signed up for a free trail
#Of the 20, four become paid subscribers. 

Monthly_cost<- 25 * 30
Number_of_new_customers_per_month<- (30 / 4) * 20

Monthly_income<- Number_of_new_customers_per_month * 10

#marketing ROI formula: = (Total revenue - cost)/ total investment

marketing_ROI = (Monthly_income - Monthly_cost)

print(marketing_ROI)


```

